export const FETCH_ALBUMS_REQUEST = "FETCH_ALBUMS_REQUEST";
export const FETCH_SUCCESS_LIST = "FETCH_SUCCESS_LIST";

export const FETCH_SUCCESS_LIST_ITEM = "FETCH_SUCCESS_LIST_ITEM";
export const FETCH_ERROR_LIST_ITEM = "FETCH_ERROR_LIST_ITEM";

export const FETCH_ERROR_LIST = "FETCH_ERROR_LIST";
